version: '2.1'

orbs:
  aws-cli: circleci/aws-cli@2.0

executors:
  aws-cli-executor:
    docker:
      - image: amazon/aws-cli

jobs:
  build:
    docker:
      - image: cimg/base:stable

    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_REGION: $AWS_REGION

    steps:
      - checkout

      - run:
          name: Set short git commit SHA
          command: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $BASH_ENV && source $BASH_ENV

      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli

      - aws-cli/setup

      - run:
          name: Login to Amazon ECR
          command: |
             aws ecr get-login-password --region $AWS_REGION --no-include-email | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      # Your existing steps...

      - run:
          name: Update kube config
          command: aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      - run:
          name: Deploy to EKS
          command: |
            helm upgrade --install nodeapp-33 helm/chart/ --set image.tag=$COMMIT_SHA
