version: 2.1

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      AWS_ACCESS_KEY_ID: 'AKIAVPAYF53GZT6XPI4M'
      AWS_SECRET_ACCESS_KEY: '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'
      AWS_REGION: 'us-east-2'
      AWS_ACCOUNT_ID: '375860358861'
      ECR_REPOSITORY: 'poc-2'
      EKS_CLUSTER_NAME: 'sanjaycluster'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short git commit SHA
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $BASH_ENV && source $BASH_ENV

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # Add the rest of your steps here
