name: Your Workflow Name

on:
  push:
    branches:
      - main  # Define the branch to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short git commit SHA
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $BASH_ENV
          source $BASH_ENV

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Add Pritunl APT repository
        run: |
          echo "deb https://repo.pritunl.com/stable/apt focal main" | sudo tee /etc/apt/sources.list.d/pritunl.list
          sudo apt --assume-yes install gnupg
          gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 7568D9BB55FF9E5287D586017AE645C0CF8E292A
          gpg --armor --export 7568D9BB55FF9E5287D586017AE645C0CF8E292A | sudo tee /etc/apt/trusted.gpg.d/pritunl.asc
          sudo apt update -y
          sudo apt install pritunl-client-electron -y
          sudo which pritunl-client
          pritunl-client
          /usr/bin/pritunl-client
          systemctl status pritunl-client.service

      - name: Test Docker connectivity
        run: docker --version

      - name: Login to Amazon ECR
        run: |
          echo "AWS_REGION: $AWS_REGION"
          echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
          export AWS_CLI_DISABLE_PROMPT=1
          aws ecr get-login-password --region $AWS_REGION | dock
